# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: kdump-utils.spec

# add or remove files that should be synced
files_to_sync:
    - kdump-utils.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: kdump-utils
# downstream (Fedora) RPM package name
downstream_package_name: kdump-utils

upstream_tag_template: v{version}
