name: kdump-utils tests

on: [pull_request, workflow_dispatch]

jobs:
  tmt-e2e-tests:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.fedora_version }}-${{ matrix.test }}
        cancel-in-progress: true
    strategy:
        matrix:
            fedora_version: [
                    "42"
            ]
        fail-fast: false

    timeout-minutes: 480
    steps:
      - uses: actions/checkout@v6

      - name: Build Fedora systemd image
        run: |
          cat > Containerfile <<'EOF'
          FROM quay.io/fedora/fedora:latest
          RUN dnf install -y systemd && dnf clean all
          STOPSIGNAL SIGRTMIN+3
          CMD ["/sbin/init"]
          EOF
          podman build -t fedora-systemd -f Containerfile .

      - name: Start container
        run: |
          podman run -d --name fedora-systemd \
            --privileged \
            --systemd=always \
            --cgroupns=host \
            -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
            -v /dev:/dev \
            -v "$GITHUB_WORKSPACE":/__w/workspace:rw \
            fedora-systemd

      - name: Wait for systemd
        run: |
          podman exec fedora-systemd systemctl restart dbus
          podman exec fedora-systemd systemctl is-system-running --wait || true

      - name: Install dependencies and start libvirtd
        run: |
          podman exec fedora-systemd dnf install -y git rpm-build make tmt+provision-virtual
          podman exec fedora-systemd systemctl start libvirtd
          podman exec fedora-systemd systemctl status libvirtd
          podman exec fedora-systemd bash -c 'test -e /dev/kvm && echo "KVM OK" || echo "WARNING: /dev/kvm missing"'
          podman exec fedora-systemd virsh list --all

      - name: Run e2e test (${{ matrix.plan }})
        run: |
          podman exec fedora-systemd bash -c '
            git config --global --add safe.directory /__w/workspace
            cd /__w/workspace/kernel-tests-plans && tmt run -B finish provision -h virtual -c system -i fedora:43 plans --name ssh
            # tools/run-integration-tests.sh ${{ matrix.fedora_version }}
          '

      - name: Fix permissions for artifacts
        if: always()
        run: |
          podman exec fedora-systemd chmod -R a+rX /var/tmp/tmt || true

      - name: Upload tmt artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: tmt-run-${{ matrix.plan }}
          path: /var/tmp/tmt/run*
          if-no-files-found: ignore
