name: kdump-utils tests

on: [pull_request, workflow_dispatch]

jobs:
  tmt-e2e-tests:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.fedora_version }}-${{ matrix.test }}
        cancel-in-progress: true
    strategy:
        matrix:
            fedora_version: [
                    "42"
            ]
        fail-fast: false

    timeout-minutes: 480
    steps:
      - uses: actions/checkout@v6

      - name: Start Fedora container with systemd
        run: |
          mkdir -p /var/tmp/tmt
          docker run -d --name fedora-systemd \
            --privileged \
            --cgroupns=host \
            -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
            -v /dev:/dev \
            -v /var/tmp/tmt:/var/tmp/tmt:rw \
            -v "$GITHUB_WORKSPACE":/__w/kdump-utils/kdump-utils:rw \
            -w /__w/kdump-utils/kdump-utils \
            --stop-signal SIGRTMIN+3 \
            quay.io/fedora/fedora:latest /sbin/init

      - name: Wait for systemd to initialize
        run: |
          docker exec fedora-systemd bash -c '
            until [ "$(systemctl is-system-running 2>/dev/null)" = "running" ] || \
                  [ "$(systemctl is-system-running 2>/dev/null)" = "degraded" ]; do
              sleep 1
            done
          '

      - name: Install dependencies and start libvirtd
        run: |
          docker exec fedora-systemd dnf install -y git rpm-build make tmt+provision-virtual
          docker exec fedora-systemd systemctl start libvirtd
          docker exec fedora-systemd systemctl status libvirtd
          docker exec fedora-systemd bash -c 'test -e /dev/kvm && echo "KVM OK" || echo "WARNING: /dev/kvm missing"'
          docker exec fedora-systemd virsh list --all

      - name: Run e2e test (${{ matrix.plan }})
        run: |
          docker exec fedora-systemd bash -c '
            git config --global --add safe.directory /__w/kdump-utils/kdump-utils
            cd kernel-tests-plans && tmt run -B finish provision -h virtual -c system -i fedora:43 plans --name ssh
            # tools/run-integration-tests.sh ${{ matrix.fedora_version }}
          '

      - name: Fix permissions for artifacts
        if: always()
        run: |
          docker exec fedora-systemd chmod -R a+rX /var/tmp/tmt || true

      - name: Upload tmt artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: tmt-run-${{ matrix.plan }}
          path: /var/tmp/tmt/run*
          if-no-files-found: ignore
