name: Add Reviewed-by

on:
  pull_request_review:
    branches:
      - main
    types:
      - submitted

jobs:
  checkout:
      runs-on: ubuntu-latest
      steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
            ref: ${{github.event.pull_request.head.ref}}
            repository: ${{github.event.pull_request.head.repo.full_name}}

  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: ntessore/add-reviewed-by-action@v1
